app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
ac_media:
    resource: "@ACMediaBundle/Controller/"
    type:     annotation
    prefix:   /    

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
    
sample:
    path:     /ajax/sample
    defaults: { _controller: ACMediaBundle:Ajax:sample }

upload_file:
    path:     /ajax/uploadFile
    defaults: { _controller: ACMediaBundle:Ajax:uploadFile }    