app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
ac_media:
    resource: "@ACMediaBundle/Controller/"
    type:     annotation
    prefix:   /    

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    